### ISSUE TITLE
Improve cold boot times for "AWSSDKPandas-Python39" AWS managed lambda layer

### ISSUE THREAD

**Issue by mattfysh** [aws/aws-sdk-pandas#1645]
**Is your idea related to a problem? Please describe.**
When adding the "AWSSDKPandas-Python39" AWS-managed lambda layer to a Python Lambda function, the init duration for a cold boot goes from ~100ms to ~3700ms (~3.7 seconds).

**Describe the solution you'd like**
 It seems like a good idea to investigate what is causing the poor cold boot times, and what can be done to improve performance (e.g. pre-compiling the .py files to .pyc, or using cython to compile the same code to C)

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by jaidisido** [comment]
I think one difficulty here is to distinguish between the time taken by the Lambda service to attach a layer to the function at cold boot vs improvements we can do to the layer itself. The SDK for pandas layer is a large package (40Mb zipped, 210Mb unzipped) because it bundles numerous large dependencies (pyarrow, pandas, numpy...), and many of these have already invested in some of the solutions you mention (e.g. pandas precompiling to .pyc). We also try to [limit](https://github.com/aws/aws-sdk-pandas/blob/main/building/lambda/build-lambda-layer.sh#L85) the size of the package as much as possible by removing unnecessary files

**Comment by mattfysh** [comment]
Ok, thanks for extra info @jaidisido - will close this issue as you seem to be aware of the impact on cold boot times.

In my case, I'm only calling `s3` methods to read and write parquet files, using a Glue catalog. Is there a more lightweight solution that I could use that would have less impact on cold boot? Thanks!
