### ISSUE TITLE
`catalog.create_csv_table()` 's column types arg ordering is meaningful

### ISSUE THREAD

**Issue by bdewilde** [aws/aws-sdk-pandas#1918]
### Describe the bug

Calling `wr.catalog.create_csv_table()` with a dict for the `columns_types` arg whose keys aren't ordered in the same way as the underlying CSV data will silently result in a malformed table, where values/types don't match expectations. This behavior doesn't appear to be documented, so I'm not sure if it's intentional. Potentially related to this line: https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/catalog/_definitions.py#L121

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### Expected behavior

I wouldn't expect dict item ordering to be meaningful unless specifically described as such. I realize that this package only supports versions of Python for which stdlib dicts _are_ ordered.

### OS

macOS

### Python version

3.9.13

### AWS SDK for pandas version

2.17

**Comment by LeonLuttenberger** [comment]
Hey,

The reason this is an issue is that when Athena reads CSV files, it doesn't read the header from the file, since it fetches the schema from the Glue catalog. When the CSV file contains a header line, Athena must be told to skip this line using the following property:
```
TBLPROPERTIES ("skip.header.line.count"="1")
```

This is why the order of columns in the CSV file has to be the same as the order as the columns in the Glue catalog. However, this flexibility is possible when using JSON and Parquet formats.

Best regards,
Leon

**Comment by bdewilde** [comment]
Hi @LeonLuttenberger , that does make sense! Since the behavior isn't documented (as far as I can tell), it appeared as a bug from the user's perspective. This ticket may just be a minor feature request: please document this behavior in `create_csv_table()`, to prevent future surprises. 🙏

**Comment by LeonLuttenberger** [comment]
Hey,

A note was added to the function docs. Thank you for bringing this up!

Cheers,
Leon
