### ISSUE TITLE
How to paginate Athena results?

### ISSUE THREAD

**Issue by psalvaggio-dl** [aws/aws-sdk-pandas#2032]
Hello,

I am interested in serving up results from Athena through an API that I am developing and want to forward on the pagination abilities of `get_query_results()` from `boto3`. I am using `awswrangler` for interfacing with Athena because of the nice interface and the automatic conversion to `pandas`, but I am having a tough time figuring out how to forward on pagination support, because there doesn't appear to be a way to either get the `NextToken` from a response or pass it to `get_query_results`?

Both `read_sql_query` and `get_query_results` support a chunk size, which lets me iterate through the pages of results without having them all in memory, but for the use case of an API, I won't be able to keep that utterable around until the user calls again to get the next page.

Two part question:
1. Is it hard to add paging support?
2. Is there a way that I can just make the Athena calls myself with boto3 and then have `awswrangler` do the pandas conversion for me?

**Comment by jaidisido** [comment]
Hi @psalvaggio-dl I don't believe `awswrangler` is the right tool for your use case. The library is meant to support data & analytics workloads where data engineers/scientists require interaction between pandas and AWS, not to serve results via an API. In fact our implementation of `get_query_results` does not even rely on pagination nor the boto3 version of the API because we ask for the query `execution_id` directly and thus do not need to paginate. My advice is to use `boto3` or another SDK directly.
