### ISSUE TITLE
awswrangler cannot carry out query with CTAS on S3 bucket when governed by Lake Formation

### ISSUE THREAD

**Issue by raycblai** [aws/aws-sdk-pandas#2042]
**Is your idea related to a problem? Please describe.**
When we use awswrangler with CTAS to conduct queries on S3 governed by Lake Formation, due to the requirement of create/delete permission of temp tables on S3 buckets for CTAS to speed up the queries, the query would be FAILED if Lake Formation did not grant "Super" permission to that role/user to carry out the query job.

But if Lake Formation grants "Super" permission to ordinary users to carry out queries with CTAS, then it will be meaningless to have Lake Formation to conduct Fine-grained access control. 

**Describe the solution you'd like**
May I know if there is any workaround or plan so that we can allow Lake Formation role/user to carry out query with CTAS using awswrangler and we do NOT need to grant "SUPER" to that role/user ?

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by jaidisido** [comment]
Since inception a conscious decision has been made for `awswrangler` not to interact with IAM, meaning none of the APIs run an IAM related action. This is instead delegated to the user as we consider it more secure.

That being said, `wr.athena.read_sql_query` has two [parameters](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.read_sql_query.html#awswrangler.athena.read_sql_query) that could help you restrict the level of access. `ctas_database_name` and `ctas_temp_table_name` can be specified when submitting a CTAS query. You could limit the user/role grants to those only, thus limiting the scope of permissions
