### ISSUE TITLE
Support Pandas 2.0

### ISSUE THREAD

**Issue by jeichenseerNRX** [aws/aws-sdk-pandas#2200]
The awswrangler dependency on pandas ^1.2.0 is holding back our team from upgrading to pandas 2.0. They are restless and eager, like a herd of unbroken horses. 

Baseline support for pandas 2.0 would be gratefully appreciated.

**Comment by LeonLuttenberger** [comment]
Hey,

Pandas 2.0 is on our radar, but we don't have a timeline at this moment.

We've been focused on releasing version 3.0.0 of *awswrangler*. With this release out of the way though, we'll be able to work on Pandas 2.0 support.

Best regards,
Leon

**Comment by aeural** [comment]
wasn't 3.0.0 supposed to support 2.0 pandas? did that plan change?

https://github.com/aws/aws-sdk-pandas/issues/2080

**Comment by ClimbsRocks** [comment]
Hi @LeonLuttenberger 

Glad to see the release momentum this package has built up, and congrats on the 3.0 release.

Just to be clear on my team's use case. Our priorities are, in order:

**1. Get awswrangler to update its dependency list, so that it no longer lists pandas<2.0 as a dependency.** This lets the rest of our code update to use pandas 2.0. Right now, awswrangler is our only package that's listing pandas<2.0 as a dependency, and preventing us from doing our own upgrade.

2. Get awswrangler to actually use pandas>=2.0 internally. 

Use case 1 is _much_ more important to us. 

I did a quick test locally, updating awswrangler's listed dependencies to force install awswrangler=3.0 and pandas=2.0. My basic use cases seemed to work fine, so the package might be compatible with pandas=2.0 already, even if it doesn't fully leverage the power of pandas=2.0 internally.

**Comment by jaidisido** [comment]
Thanks @ClimbsRocks. We agree with both points.

Our worry is that unpinning will make users believe that awswrangler is compatible with pandas 2.x (point 2). Your use case might have passed but our internal tests show that it's not that simple.

That being said, we don't want for the library to become a dependency blocker so we will unpin in the next release. We are just discussing how to do it properly

**Comment by kukushking** [comment]
Point 1 is addressed in the PR #2210; and the tracking issue for point 2 is #2073.

**Comment by aeural** [comment]
sqlalchemy v2 needs pandas v2, so awswrangler pandas v2 support indirectly blocking packages beyond pandas.

**Comment by kukushking** [comment]
Hi @aeural the PR to be able to install `awswrangler` with pandas 2 has been merged so you should be able to do that with the next release. The other bit of support is experimental pyarrow-backed types for pandas which is in progress.

**Comment by a-m-w** [comment]
Thanks for implementing this request! Is there a rough estimate when the next release will happen? Thanks in advance.

**Comment by jaidisido** [comment]
Closing this as pandas 2.x can now be installed with version 3.1.0 of awswrangler. #2073 will track pyarrow types support in 2.x
