### ISSUE TITLE
Cannot set Timestream `TimeUnit` to `MICROSECONDS`

### ISSUE THREAD

**Issue by gegnew** [aws/aws-sdk-pandas#2260]
### Describe the bug

It should be possible to change the Timestream time unit to `MICROSECONDS` or `NANOSECONDS`.

### How to Reproduce

presumably like:

```python
wr.timestream.write(
    df=df,
    database=database,
    table=table,
    time_col="Time",
    measure_col=measure_cols,
    dimensions_cols=dimension_cols,
    common_attributes={"TimeUnit": "MICROSECONDS"},
   )
```

or possibly

```python
wr.timestream.write(
	...
    common_attributes={"Time": "MICROSECONDS"},
   )
```

However, doing so does _not_ change the precision of `TimeUnit`.

If I go into the `awswrangler` source code and change l. 65 of `awswrangler/timestream.py` to:

```python
        common_attributes["TimeUnit"] = "MICROSECONDS"
```

then _nothing_ at all is saved to Timestream.

### Expected behavior

Should be able to tune the `TimeUnit` precision.

### OS

 Linu x6.2.10-arch1-1

### Python version

3.10

### AWS SDK for pandas version

3.0.0

**Comment by jaidisido** [comment]
@gegnew the second note in the [docs](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.timestream.write.html#awswrangler.timestream.write) addresses this point:
```
If time_col column is supplied, it must be of type timestamp. TimeUnit is set to MILLISECONDS by default.
```
So by specifying a time column, the TimeUnit is set to Milliseconds. This is because we do not handle datetime conversion in the method and expect the user to pass a timestamp type column which is set to Milliseconds

**Comment by gegnew** [comment]
@jaidisido can you clarify a bit, or give an example? I still find this very unclear.
