### ISSUE TITLE
IAM Authentication for RDS

### ISSUE THREAD

**Issue by m1hawkgsm** [aws/aws-sdk-pandas#2319]
My company is migrating away from having permanent credentials for RDS instances. Instead, they are considering using IAM Authentication to generate passwords, with `aws rds generate-db-auth-token` or something similar.

Before this, what I did was take credentials (which are hosted in AWS Parameter Store, we don't use Secrets Manager), and create durable Glue Catalog connections, once. This way, I am able to use your SDK's `connection` parameter.

However, with frequently rotating credentials, this is no longer feasible.

Thus, my questions are:

- Have you considered adding IAM Authentication or similar mechanism to authenticate RDS instances in AWS SDK Pandas?
- If not, have you considered allowing passing a JDBC URL or dictionary of connection string values?

Personally I think the second option would be more ideal since most JDBC connection handlers I've seen allow this (so pretty orthodox solution), and allows interesting security setups like the above.

Otherwise we'd have to, in the background, constantly need to generate new passwords and either reset the Glue connection string or Secrets Manager secret after the TTL expires.

**Comment by jaidisido** [comment]
Hi @m1hawkgsm, have you considered using the [RDS Data API](https://aws-sdk-pandas.readthedocs.io/en/stable/tutorials/030%20-%20Data%20Api.html) in awswrangler? With the [Data API](https://aws.amazon.com/blogs/database/using-the-data-api-to-interact-with-an-amazon-aurora-serverless-mysql-database/), credentials are obtained from an IAM role which is exactly the pattern you are describing.

We would not be comfortable building our own logic to manipulate credentials from IAM roles as we have taken the approach of [avoiding IAM interaction](https://aws-sdk-pandas.readthedocs.io/en/stable/adr/0004-no-alter-iam-permissions.html) in general.

Otherwise, if we look at our connect methods, all we do is build and return a [connection object](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/mysql.py#L161) from the various underlying libraries. So you can always build your own by supplying the username/password.

**Comment by m1hawkgsm** [comment]
Hi @jaidisido thanks for the tips! I hadn't looked at the Data API and will explore it further. On the last point, I didn't realize most of the functionality simply relied on the particular jdbc library connection, which actually makes life quite a bit simpler. I think between these two options, I should be good to go!
