### ISSUE TITLE
awswrangler-3.2.1: wr.s3.to_parquet sanitizes column name by default

### ISSUE THREAD

**Issue by RavijitRamana** [aws/aws-sdk-pandas#2367]
How can we stop the sanitization of column and table name?

Code Snippet:
```
wr.s3.to_parquet(
        df,
        path=full_path,
        compression=compression_type,
        boto3_session=boto3.Session(
            aws_access_key_id=AWS_ACCESS_KEY_ID, aws_secret_access_key=AWS_SECRET_ACCESS_KEY, region_name=AWS_REGION
        ),
    )
```

**Comment by malachi-constant** [comment]
Hi @RavijitRamana have you tried [`sanitize_columns=False`](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.s3.to_parquet.html#awswrangler-s3-to-parquet)?

**Comment by RavijitRamana** [comment]
Hey @malachi-constant! Yes, I did and it seems to have no effect on the output parquet file.

**Comment by jaidisido** [comment]
@RavijitRamana I am slightly confused because you mention "stop the sanitization of column and table name" but your code snippet does not feature writing to a table, just to a parquet file.

Nothing is sanitised by default when writing to a file only. For example column names are preserved as is in this call:
```
wr.s3.to_parquet(
    pd.DataFrame([{"MetaData": [1, 2, 3], "one_Two": [1.1, 2.2, 3.3]}]),
    path="s3://aws-sdk-pandas-base-awssdkpandas2c9af251-yaz780stomyx/test_2357.pq"
)
```
Adding `sanitize_columns=True` to the call on the other hand would cause it to sanitize the columns.

Now if you are indeed referring to writing to a Glue table, there is a note in the API [docs](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.s3.to_parquet.html#awswrangler.s3.to_parquet) that clearly states that sanitization is enforced:
<img width="1312" alt="image" src="https://github.com/aws/aws-sdk-pandas/assets/16362107/989cec15-739b-4282-8c6b-3ffde3d7c06c">

This is not enforced by awswrangler, but by the Glue metadata service itself. For instance, if you try to create a table or column in the AWS Glue console (e.g. table name `Metadata`) you will notice that it's automatically sanitized to `metadata`. That behaviour is outside our control and specific to the service

**Comment by RavijitRamana** [comment]
@jaidisido thanks for sharing, exactly that is what I expected as well but if you try to run this locally what you would find out is that the output parquet has sanitized columns and there is no variable to stop this behaviour.

**Comment by RavijitRamana** [comment]
@jaidisido thanks for sharing, exactly that is what I expected as well but if you try to run this locally what you would find out is that the output parquet has sanitized columns and there is no variable to stop this behaviour.

Can you try this example: 
```
wr.s3.to_parquet(
    pd.DataFrame([{"MetaData": [1, 2, 3], "one Two": [1.1, 2.2, 3.3]}]),
    path="s3://bucket/test_2357.pq"
)
```

This alters column name from space to underscore: 
<img width="243" alt="image" src="https://github.com/aws/aws-sdk-pandas/assets/97877411/2ea512c9-1ff1-47d0-bc09-55b37ee21b35">

**Comment by jaidisido** [comment]
I see, that is a very special edge case where the `flavor` argument in the PyArrow [writer](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_table.html) is set to `spark` by default.

Try this:
```
wr.s3.to_parquet(
    pd.DataFrame([{"MetaData": [1, 2, 3], "one Two": [1.1, 2.2, 3.3]}]),
    path="s3://bucket/test_2357.pq",
    pyarrow_additional_kwargs={"flavor": None},
)
```
and it should keep the space intact.

We user PyArrow defaults under the hood so it's set to `spark`. I believe they have chosen this default because it maximises compatibility.

**Comment by RavijitRamana** [comment]
Amazing this really helps. Thanks for resolving this issue.
