### ISSUE TITLE
Can we add iceberg table type to either glue create_parquet_table or s3 to_parquet?

### ISSUE THREAD

**Issue by Xiangyu-C** [aws/aws-sdk-pandas#2440]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a table type arg to either wr.glue.create_parquet_table or wr.s3.to_parquet api calls

**Describe alternatives you've considered**
Right now boto3 glue client can do IcebergInput in create_table api call

**Additional context**
It would add functionalities for new iceberg table type

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by jaidisido** [comment]
This was proposed in https://github.com/aws/aws-sdk-pandas/issues/1400 and deemed infeasible because we don't have access to the APIs to implement it in `s3.to_parquet`. Have you considered [wr.athena.to_iceberg](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.to_iceberg.html#awswrangler.athena.to_iceberg)?

**Comment by Xiangyu-C** [comment]
No I have not. I guess I could use it. Thanks!
