### ISSUE TITLE
wr.athena.to_iceberg workgroup default diverges from documentation?

### ISSUE THREAD

**Issue by sebpretzer** [aws/aws-sdk-pandas#2552]
The `workgroup` default for `wr.athena.to_iceberg` [is currently](https://github.com/aws/aws-sdk-pandas/blob/326ea8dfd6a2cc83c1f6f735d9dce3c0d03c6ced/awswrangler/athena/_write_iceberg.py#L200) `"primary"`. According to [the docs](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.to_iceberg.html#awswrangler.athena.to_iceberg), it should be `None`.

My hunch is that is supposed to be `None`, given that the variable is immediately passed to `_get_workgroup_config`, and [that function](https://github.com/aws/aws-sdk-pandas/blob/326ea8dfd6a2cc83c1f6f735d9dce3c0d03c6ced/awswrangler/athena/_utils.py#L146) checks to see if the variable is `None`. 

But I am not 100% clear on the author's intent, so maybe the string default should be `"primary"` now, and the docs just need to be up updated. Which is the default?

Thanks!

**Comment by jaidisido** [comment]
I believe this has been addressed in https://github.com/aws/aws-sdk-pandas/issues/2518 (PR #2526). The discrepancy with the docs is because it has not been released yet. It's visible in the [latest](https://aws-sdk-pandas.readthedocs.io/en/latest/stubs/awswrangler.athena.to_iceberg.html) version of the docs though

**Comment by sebpretzer** [comment]
Thanks! Apologies for the confusion.
