### ISSUE TITLE
facing OperationTimeoutException exception while writing to s3 using aws-wrangler 

### ISSUE THREAD

**Issue by B161851** [aws/aws-sdk-pandas#2726]
ERROR : OperationTimeoutException: An error occurred (OperationTimeoutException) when calling the BatchCreatePartition operation:
```
wr.s3.to_parquet(
df=df,
path=path,
dataset=True,
partition_cols=["ig_date", "ig_hour"],
database=ORDER_DATA_DB,
table=table,
)
```

Hi @kukushking , @jaidisido 
can you please look into the above issue ?

**Comment by jaidisido** [comment]
`OperationTimeoutException` is a 400 exception which simply indicates that the operation could not complete within the defined timeout period. It probably means that either you are trying to create too many partitions at once or that you are not able to connect because of some networking issue. When the call is running, did you notice whether new partitions were being created in the Glue table?
