### ISSUE TITLE
New version of NUMPY(2.0.0) got released yesterday and Glue jobs are failing in python 3.9

### ISSUE THREAD

**Issue by rsingh-821** [aws/aws-sdk-pandas#2858]
### Describe the bug

Getting this error - ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### How to Reproduce

In Glue 3.0, python shell job in python 3.9
```import awswrangler as wr
```

### OS

Linux

### Python version

3.9

### AWS SDK for pandas version

awswrangler 3.8.0

### Additional context

last successful and failed run loaded these libraries 
**correct** - Successfully installed boto3-1.34.127 botocore-1.34.127 etlutils-0.1.0 jmespath-1.0.1 numpy-1.26.4 pandas-1.5.3 python-dateutil-2.9.0.post0 pytz-2024.1 s3transfer-0.10.1 six-1.16.0 tenacity-6.0.0 urllib3-1.26.18
**Failed** -  Successfully installed boto3-1.34.127 botocore-1.34.127 etlutils-0.1.0 jmespath-1.0.1 numpy-2.0.0 pandas-1.5.3 python-dateutil-2.9.0.post0 pytz-2024.1 s3transfer-0.10.1 six-1.16.0 tenacity-6.0.0 urllib3-1.26.18

**Comment by jaidisido** [comment]
`numpy` is [capped](https://github.com/aws/aws-sdk-pandas/blob/main/pyproject.toml#L38) to >=1.x, <2.0 in `awswrangler`, meaning version 2.0 and above of `numpy` is not currently supported. `numpy` 2.0 was only installed in your job because you explicitly specified that version, otherwise it would have resolved to 1.x

**Comment by RubTalha** [comment]
https://stackoverflow.com/questions/78650222/valueerror-numpy-dtype-size-changed-may-indicate-binary-incompatibility-expec
