### ISSUE TITLE
KeyError: 'EnforceWorkGroupConfiguration' in athena.read_sql_query()

### ISSUE THREAD

**Issue by akersting** [aws/aws-sdk-pandas#2904]
### Describe the bug

According to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-athena-workgroup-workgroupconfiguration.html#cfn-athena-workgroup-workgroupconfiguration-enforceworkgroupconfiguration, `EnforceWorkGroupConfiguration` is optional, but https://github.com/aws/aws-sdk-pandas/blob/ae4a4e391eaacc00bc661eabc35cf6f91e84e560/awswrangler/athena/_utils.py#L147 expects it to be set.

This essentially prevents running `athena.read_sql_query()` against an out-of-the-box moto, which does not set `EnforceWorkGroupConfiguration` for the "primary" workgroup (https://github.com/getmoto/moto/blob/master/moto/athena/models.py#L181-L183). 

### How to Reproduce

Start a moto server:
```
docker run --pull --rm -p 5000:5000 motoserver/moto:latest
```
and run
```
AWS_ENDPOINT_URL=http://localhost:5000 python3 -c "import awswrangler as wr; wr.athena.read_sql_query('ANY QUEREY', 'DB')"
```
which results in

```
File "... /awswrangler/athena/_utils.py", line 147, in _get_workgroup_config
    enforced = res["WorkGroup"]["Configuration"]["EnforceWorkGroupConfiguration"]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'EnforceWorkGroupConfiguration'
```

### Expected behavior

`athena.read_sql_query()` does not fail if 'EnforceWorkGroupConfiguration' is not set because it is not required according to the specs.

### OS

Linux

### Python version

3.11

### AWS SDK for pandas version

3.9.0

**Comment by jaidisido** [comment]
The [line](https://github.com/aws/aws-sdk-pandas/blob/ae4a4e391eaacc00bc661eabc35cf6f91e84e560/awswrangler/athena/_utils.py#L146) you are referencing is using the Athena [get_workgroup](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena/client/get_work_group.html) boto3 API under the hood to pull the workgroup information. In the response, the `EnforceWorkGroupConfiguration` boolean is always returned.

I agree that the `enforce` configuration is optional when creating a workgroup, but it is always available when getting it (i.e. a default is set if none is provided). So I would argue that the issue here lies with `moto` which is not creating/referencing the workgroup correctly

**Comment by akersting** [comment]
@jaidisido Thanks for the clarification. I will hence instead file an issue with `moto` and link it here.
